package pl.edu.pjwstk.engineeringthesis.util

const val PROFILE_DEFAULT_TEMPERATURE_LOW = 36.5f
const val PROFILE_DEFAULT_TEMPERATURE_HIGH = 37.3f
const val PROFILE_DEFAULT_TEMPERATURE_OFFSET_C = 0f
const val PROFILE_DEFAULT_HEART_RATE_LOW = 60f
const val PROFILE_DEFAULT_HEART_RATE_HIGH = 100f
const val PROFILE_DEFAULT_SPO2_LOW = 97f
const val PROFILE_DEFAULT_SPO2_HIGH = 100f
const val PROFILE_DEFAULT_SKIN_CONDUCTANCE_LOW = GSR_NEUTRAL_MIN
const val PROFILE_DEFAULT_SKIN_CONDUCTANCE_HIGH = GSR_NEUTRAL_MAX

const val PROFILE_CALIBRATION_TEMPERATURE_MIN = 20f
const val PROFILE_CALIBRATION_TEMPERATURE_MAX = 46.5f
const val PROFILE_CALIBRATION_TEMPERATURE_OFFSET_MIN = -20f
const val PROFILE_CALIBRATION_TEMPERATURE_OFFSET_MAX = 20f
const val PROFILE_CALIBRATION_HEART_RATE_MIN = 20f
const val PROFILE_CALIBRATION_HEART_RATE_MAX = 270f
const val PROFILE_CALIBRATION_SPO2_MIN = 70f
const val PROFILE_CALIBRATION_SPO2_MAX = 100f
const val PROFILE_CALIBRATION_SKIN_CONDUCTANCE_MIN = GSR_SENSOR_MIN_US
const val PROFILE_CALIBRATION_SKIN_CONDUCTANCE_MAX = GSR_SENSOR_MAX_US
