package pl.edu.pjwstk.engineeringthesis.util

const val PROFILE_DEFAULT_TEMPERATURE_LOW = 36.5f
const val PROFILE_DEFAULT_TEMPERATURE_HIGH = 37.3f
const val PROFILE_DEFAULT_HEART_RATE_LOW = 60f
const val PROFILE_DEFAULT_HEART_RATE_HIGH = 100f
const val PROFILE_DEFAULT_SKIN_CONDUCTANCE_LOW = GSR_NEUTRAL_MIN
const val PROFILE_DEFAULT_SKIN_CONDUCTANCE_HIGH = GSR_NEUTRAL_MAX
